# -*- coding: utf-8 -*-
"""Projet de CONG Hoa-sheng

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwyVlIr_OluKHuVqHoXUu3VyJ3zw6ftQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('capacites-de-production-par-pays-du-groupe-edf.csv')

df.pop('Type of energy')
df.pop('Commentaire')
df.pop('Spatial perimeter')
df.pop('Sector')
df.pop('Legal perimeter')
df.pop('Consolidation method')
print(df)

df.dtypes


df.isnull()
df.isna()


df.isnull().sum()


df.info()

df.describe()

#On supprime les valeurs aberrantes

#On calcule Q1

q1=df["Capacité maximale de production"].quantile(q=0.25)

#On calcule Q3

q3=df["Capacité maximale de production"].quantile(q=0.75)

#On calcule l'écart interquartile (IQR)

IQR=q3-q1

#On calcule la borne inférieure à l'aide du Q1 et de l'écart interquartile

borne_inf = q1-1.5*IQR

#On calcule la borne supérieure à l'aide du Q3 et de l'écart interquartile

borne_sup = q3 +1.5*IQR

df1= df[df["Capacité maximale de production"]<borne_sup]
df1= df1[df1["Capacité maximale de production"]>borne_inf]
df1.describe()

yg=df1['Capacité maximale de production']


plt.boxplot(yg)
plt.show

a=df.groupby(["Filière"]).sum()
print(a)


explode = (0, 0, 0, 0, 0 ,0 ,0 ,0 ,0 ,0 ,0.1 ,0)
labels=a.index
fig1, ax1 = plt.subplots(figsize=(7, 7))

ax1.pie(a['Capacité maximale de production'] ,explode=explode ,labels=labels, autopct='%1.1f%%',
shadow=True, startangle=0)
ax1.axis('equal')
plt.show()

"""À partir de ce camembert, on peut voir que EDF produit 45% d'énergie avec le nucléaire, l'énergie produite avec les barrages hydraulique et le gaz on une bonne proportion de la production. De plus, la plupart des énergies non renouvellable sont délaissé."""

rs = df['Filière']
vi = df['Capacité maximale de production']
fig, ax = plt.subplots(figsize=(17, 9))
ax.bar(rs, vi)
ax.set(xlabel='Filière', ylabel='Capacité maximale de production'
, title= 'Capacité maximal de production en fonction de la filière')


plt.show()

"""Sur ce diagramme, comme avec le camembert, on peut observer la capacité maxiamle  de production en fonction des filières. On peut remarquer que le nucléaire a la plus grande capacité maximmale de production avec une cpacité de plus de 60 000kWh contre pratiquement 0kwh pout la Géothemie, la plus faible capacité maximale de production. On a ensuite, le Gaz et l'hydraulique, juste apres le nucleaire, plus ou moins égale avec une capacité maximale de production d'environ 22 000kWh. Le reste des énergies  est en dessous des 10 000kWh de capacité de production maximale.

# **Part II**

# **A. Récit des données (Data storytelling):**
"""

l=list(range(2019,2022))
b=df.groupby('Année')['Capacité maximale de production'].sum()
print(b)
croissant=b.tolist()
print(croissant)
fig, ax = plt.subplots()
plt.xscale('linear')
ax.set(xlabel='Année', ylabel='Capacité maximale de production'
, title= 'Evolution de la capacité maximal de production au cours du temps')
ax.set_xticks([2019,2020,2021])
ax.plot(l, croissant,
        l, croissant, "or")

plt.show()

"""Sur cette courbe, on observe une décroissance de la capacité maximale de production au cours du temps. On observe que la capacité maximale de production passe de 162 OOO kWh en 2019 à moins de 157 000 kWh. Donc une perte de capacité maximale de production de plus de 5000 kWh en 2 ans."""

df2019 = df[df.Année==2019]
df2020 = df[df.Année==2020]
df2021 = df[df.Année==2021]

df2019=df2019.groupby(["Filière"]).sum()
df2020=df2020.groupby(["Filière"]).sum()
df2021=df2021.groupby(["Filière"]).sum()

labels1=df2019.index
labels2=df2020.index
labels3=df2021.index

fig1, ax1 = plt.subplots(figsize=(5, 5))
ax1.pie(df2019['Capacité maximale de production'], labels=labels, autopct='%1.1f%%',
shadow=True, startangle=0)
plt.title('2019')
plt.show()

fig2, ax2 = plt.subplots(figsize=(5, 5))
ax2.pie(df2020['Capacité maximale de production'], labels=labels, autopct='%1.1f%%',
shadow=True, startangle=0)
plt.title('2020')
plt.show()

fig3, ax3 = plt.subplots(figsize=(5, 5))
ax3.pie(df2021['Capacité maximale de production'], labels=labels, autopct='%1.1f%%',
shadow=True, startangle=0)
plt.title('2021')
plt.show()

"""Grâce à ce code nous pouvons comparer l'évolution des pourcentages d'energie au cours du temps. 
On peut voir que lorsque le nucléaire baisse, la part de l'énergie hydraulique et du gaz augmentent. 
Les energies renouvellables comme l'éolien et le solaire on une part fleurissante"""

